mongo_uri: ${MONGO_URI:mongodb://localhost/convai}

facebook:
  page_access_token: ${FB_PAGE_ACCESS_TOKEN:<none>}
  webhook: ${FB_WEBHOOK:https://2258.lnsigo.mipt.ru/fb}
  webhook_secret: ${FB_WEBHOOK_SECRET:<none>}

telegram:
  webhook: ${TG_WEBHOOK:https://2258.lnsigo.mipt.ru/tg}
  token: ${TG_TOKEN:<none>}

dialog:
  max_time_in_lobby: 1
  human_bot_ratio: 0.0
  inactivity_timeout: 300
  max_length: 1000
  evaluation_score_from: 1
  evaluation_score_to: 5
  n_bad_messages_in_a_row_threshold: 10
  guess_profile_sentence_by_sentence: false
  allow_set_bot: true
  reveal_dialog_id: false

evaluation_options:
  score_dialog: false
  guess_profile: false

logging:
  root_path: ~/log/convai-router
  base_level: DEBUG